### PR TITLE
Workaround to randomly failing tests: dropDatabase after each test run

### PR DESCRIPTION
**Pull request by tinchodias**
This is not a real fix to the bug, but it is too annoying to have the tests failing. Instead, I created #testSelectAllJustAfterRemove which spots the bug. This way, there is 1 fail instead of many random.

### CODE REVIEW

**Comment by tinchodias** [comment]
This would close issue #8

**Comment by tinchodias** [comment]
Ouch. There is a merge conflict because my fork was done before Esteban added the Mongo tests to Travis script... and now I removed them back, because it's too noisy for new developments to have red builds in Travis.

**Comment by estebanlm** [comment]
merge and re-send :)

**Comment by tinchodias** [comment]
Merged! (next contribution will be cleaner)

**Comment by tinchodias** [comment]
ready

**Comment by estebanlm** [comment]
merged... wow, dropping database makes tests take ~10m! :smile:

**Comment by tinchodias** [comment]
We could try a faster operation. In fact, removeAll + delay 100
milliseconds or so was another possible workaround. But looks uglier.

**Pull request merged**
