### PR TITLE
In collectionAt:inDatabase:, replace addCollection: by getCollection: 

### LINKED ISSUE #14: Test Runner on VORepositoryTest hangs with MongoTalk 1.9.1 (released some days ago)
Debugging and backtracking the error, I narrowed the error to a change introduced in Mongo-Core-HolgerHansPeterFreyther.44. What I found is that the new implementation of MongoDatabase>>addCollection: no longer tolerates adding an already existing collection.

This is how adding a collection works, before and after:

- before (directly in `MongoDatabase>>addCollection:`) 

	| command reply |
	command := Dictionary new.
	command at: 'create' put: aString.
	reply := self command: command.
	reply at: 'ok' ifAbsent: [self halt].
	^MongoCollection database: self name: aString

- currently (delegated to `MongoDatabase>>addCollection:capped:size:max:`)

	| command reply |
	command := SmallDictionary new.
	command at: 'create' put: aString.
	aCapped ifTrue: [
		command at: 'capped' put: true.
		aSize ifNotNil: [command at: 'size' put: aSize].
		aMax ifNotNil: [command at: 'max' put: aMax]].
	reply := self command: command.
	(reply at: 'ok' ifAbsent: [self halt]) = 1.0 ifFalse: [
		^self error: 'Command failed'.
	].
	^MongoCollection database: self name: aString

I didn't analyse why the tests add an existing collection. So not sure if it's the test or the code that should be fixed.

But, I tried inserting the following code to tolerate adding an existing collection, and it worked fine:

	(reply at: 'ok' ifAbsent: [self halt]) = 1.0 ifFalse: [		
		"Tolerate error 48: collection already exists"
		((reply at: 'code') = 48) ifFalse: [ ^self error: 'Command failed' ]
	].

The code is not nice, but I can commit it if you agree. No idea why Travis builds don't complain on this, but I reproduced the hang on my linux in Pharo 3, 4 and 5.

Opinions?

### PR DESCRIPTION
**Pull request by tinchodias**
I realized this change was necessary after @noha's change in Mongo. This would close #14.

### CODE REVIEW

**Comment by noha** [comment]
Thanks for integration. Sad but true we have a bigger problem overall. Most of the old versions of Voyage load MongoTalk stable which is not backward compatible. So I cannot use an old version. We should just stop to use symbolic versions in dependencies. It's a drag!

**Comment by noha** [comment]
As long as Voyage is broken can we make a 1.3.1 version of Voyage that uses an old version of MongoTalk? What do you think?

**Comment by estebanlm** [comment]
yes, please

**Comment by noha** [comment]
I've released 1.3.1.1 that uses mongo talk 1.6.1. 1.6.1 was the stable version at the point voyage 1.3.1 was released. I've made it the stable for pharo3.x. pharo 4 and 5 have newer versions and I'm not sure what to do. IMHO everything after 1.3.1 is broken. Should be use 1.3.1.1 as stable for other versions, too?

**Comment by tinchodias** [comment]
hi @noha 

+1 I'm a new user but that sounds correct. I don't think why pharo 4 and 5 would use different stable versions. There was the fix of the Timestamp warning in pharo 5 but that was not a big deal.

+1 to your change: I agree, the Metacello versions should point to concrete dependency versions. I didn't realize of this problem.

**Pull request merged**
